/**
 * Curated Google Fonts (~150) for the editor picker — searchable, one CSS request per family when used.
 * Not the full Google catalog (1000+) to keep the JS bundle small; users can paste custom CSS stacks.
 */
export const GOOGLE_FONT_FAMILIES: readonly string[] = [
	'ABeeZee',
	'Abril Fatface',
	'Alegreya',
	'Alegreya Sans',
	'Alfa Slab One',
	'Alice',
	'Almarai',
	'Amatic SC',
	'Amiri',
	'Anton',
	'Architects Daughter',
	'Archivo',
	'Archivo Black',
	'Arimo',
	'Arvo',
	'Asap',
	'Assistant',
	'Barlow',
	'Barlow Condensed',
	'Be Vietnam Pro',
	'Bebas Neue',
	'Bitter',
	'Bodoni Moda',
	'Bree Serif',
	'Bungee',
	'Cabin',
	'Cairo',
	'Cantarell',
	'Cardo',
	'Catamaran',
	'Caveat',
	'Chakra Petch',
	'Changa',
	'Chivo',
	'Cinzel',
	'Comfortaa',
	'Commissioner',
	'Cormorant',
	'Cormorant Garamond',
	'Courgette',
	'Crimson Pro',
	'Crimson Text',
	'DM Sans',
	'DM Serif Display',
	'Dancing Script',
	'Domine',
	'Dosis',
	'EB Garamond',
	'Economica',
	'Exo',
	'Exo 2',
	'Fira Code',
	'Fira Sans',
	'Fjalla One',
	'Francois One',
	'Fraunces',
	'Fredoka',
	'Fredoka One',
	'Gelasio',
	'Geologica',
	'Georama',
	'Gloria Hallelujah',
	'Gothic A1',
	'Great Vibes',
	'Gruppo',
	'Hanken Grotesk',
	'Heebo',
	'Henny Penny',
	'Hind',
	'IBM Plex Mono',
	'IBM Plex Sans',
	'IBM Plex Serif',
	'Inconsolata',
	'Indie Flower',
	'Inter',
	'Inter Tight',
	'Josefin Sans',
	'Josefin Slab',
	'Jost',
	'Jura',
	'Just Another Hand',
	'Kanit',
	'Karla',
	'Kavoon',
	'Kdam Thmor Pro',
	'Khand',
	'Kosugi',
	'Krub',
	'Lato',
	'League Gothic',
	'League Spartan',
	'Lexend',
	'Libre Baskerville',
	'Libre Bodoni',
	'Libre Caslon Text',
	'Libre Franklin',
	'Lilita One',
	'Lobster',
	'Lora',
	'Love Light',
	'Luckiest Guy',
	'Manrope',
	'Marcellus',
	'Marck Script',
	'Merienda',
	'Merriweather',
	'Merriweather Sans',
	'Montserrat',
	'Montserrat Alternates',
	'Mukta',
	'Mulish',
	'Nanum Gothic',
	'Newsreader',
	'Niramit',
	'Noto Color Emoji',
	'Noto Sans',
	'Noto Sans JP',
	'Noto Sans KR',
	'Noto Sans SC',
	'Noto Sans TC',
	'Noto Serif',
	'Noto Serif JP',
	'Nunito',
	'Nunito Sans',
	'Open Sans',
	'Orbitron',
	'Oswald',
	'Outfit',
	'Overpass',
	'Oxygen',
	'PT Sans',
	'PT Serif',
	'Pacifico',
	'Passion One',
	'Pathway Gothic One',
	'Patrick Hand',
	'Patrick Hand SC',
	'Pattaya',
	'Patua One',
	'Permanent Marker',
	'Petrona',
	'Philosopher',
	'Play',
	'Playfair Display',
	'Playfair Display SC',
	'Plus Jakarta Sans',
	'Poppins',
	'Prata',
	'Press Start 2P',
	'Prompt',
	'Public Sans',
	'Quando',
	'Quantico',
	'Quattrocento',
	'Quattrocento Sans',
	'Questrial',
	'Quicksand',
	'Quintessential',
	'REM',
	'Radio Canada',
	'Rajdhani',
	'Rakkas',
	'Raleway',
	'Raleway Dots',
	'Rambla',
	'Rammetto One',
	'Recursive',
	'Red Hat Display',
	'Red Hat Mono',
	'Red Hat Text',
	'Righteous',
	'Roboto',
	'Roboto Condensed',
	'Roboto Flex',
	'Roboto Mono',
	'Roboto Serif',
	'Roboto Slab',
	'Rokkitt',
	'Rubik',
	'Russo One',
	'Sacramento',
	'Saira',
	'Saira Condensed',
	'Sarabun',
	'Satisfy',
	'Scada',
	'Shadows Into Light',
	'Signika',
	'Signika Negative',
	'Silkscreen',
	'Slabo 27px',
	'Smooch Sans',
	'Sniglet',
	'Sora',
	'Source Code Pro',
	'Source Sans 3',
	'Source Serif 4',
	'Space Grotesk',
	'Space Mono',
	'Special Elite',
	'Spectral',
	'Spline Sans',
	'Squada One',
	'Sriracha',
	'Staatliches',
	'Stick',
	'Stick No Bills',
	'Syne',
	'Tajawal',
	'Tangerine',
	'Teko',
	'Tenor Sans',
	'Texturina',
	'Tinos',
	'Titan One',
	'Titillium Web',
	'Tomorrow',
	'Ubuntu',
	'Ubuntu Condensed',
	'Ubuntu Mono',
	'Ultra',
	'Unbounded',
	'Urbanist',
	'Varela Round',
	'Vollkorn',
	'Work Sans',
	'Yanone Kaffeesatz',
	'Yantramanav',
	'Yellowtail',
	'Yeseva One',
	'Zen Kaku Gothic New',
	'Zilla Slab'
] as const;

export const GOOGLE_FONT_FAMILY_SET = new Set(
	GOOGLE_FONT_FAMILIES.map((f) => f.toLowerCase())
);
